apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: amazin-dev
resources:
- serviceaccounts.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
patchesStrategicMerge:
- dockercfg-default-patch.yaml
- dockercfg-builder-patch.yaml
- dockercfg-deployer-patch.yaml
commonAnnotations:
  author: Justin Davis