spring:
  application:
    name: api-gateway.build.test

server:
  port: 8080

basket:
  host: basket-amazin-dev.apps.ocp.192.168.33.11.xip.io

inventory:
  host: inventory-amazin-dev.apps.ocp.192.168.33.11.xip.io

user:
  host: basket-amazin-dev.apps.ocp.192.168.33.11.xip.io

opentracing:
  jaeger:
    enable-b3-propagation: true
    opentracing.jaeger.expand-exception-logs: true
    http-sender:
      url: http://jaeger-collector.istio-system.svc:14268/api/traces
#    udp-sender:
#      host: jaeger-collector.istio-system.svc
#      port: 14267

