apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: inventory-lb
spec:
  destination:
    name: inventory
  precedence: 1
  route:
  - labels:
      version: v1
    weight: 100
  - labels:
      version: v2
    weight: 100
  - labels:
      version: v3
    weight: 100