apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../base
patchesStrategicMerge:
- ingress-patch.yaml
- deployment-patch.yaml
namePrefix: inventory-
commonLabels:
  service: inventory

configMapGenerator:
- files:
  - config.properties
  name: inventory-config

patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: inventory-deployment
  path: deployment-json-patches.yaml