apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: service-prd-template
objects:

- apiVersion: v1
  kind: Service
  metadata:
    annotations:
    labels:
      app: ${SERVICE_NAME}
    name: ${SERVICE_NAME}
  spec:
    ports:
      - name: http
        port: 8080
        protocol: TCP
        targetPort: 8080
    selector:
      app: ${SERVICE_NAME}
    sessionAffinity: None
    type: ClusterIP
      
parameters:
  - description: The name for the service.
    name: SERVICE_NAME
    required: true
    value: "basket"


