apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: service-prd-template
objects:

- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}-$[SPRING_PROFILES_ACTIVE}-sa

- apiVersion: v1
  kind: Service
  metadata:
    annotations:
    labels:
      app: ${APPLICATION_NAME}
    name: ${SERVICE_NAME}-${SPRING_PROFILES_ACTIVE}
  spec:
    ports:
      - name: http
        port: 8080
        protocol: TCP
        targetPort: 8080
    selector:
      app: ${APPLICATION_NAME}
    sessionAffinity: None
    type: ClusterIP
      
parameters:
  - description: The name for the application.
    name: APPLICATION_NAME
    required: true
    value: "basket"
  - description: The Spring Active Profile.
    name: SPRING_PROFILES_ACTIVE
    required: true
    value: "prd"



