kind: Template
apiVersion: v1
metadata:
  labels:
    app: ${APPLICATION_NAME}
  annotations:
    description: The Keycloak Gatekeeper OpenShift template
    tags: instant-app, ${APPLICATION_NAME}
  name: openshift-deploy-template
objects:

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: ${APPLICATION_NAME}
      deploymentconfig: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    replicas: 1
    selector:
      app: ${APPLICATION_NAME}
      deploymentconfig: ${APPLICATION_NAME}
    strategy:
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          app: ${APPLICATION_NAME}
          deploymentconfig: ${APPLICATION_NAME}
      spec:
        containers:
        - env:
          image: ' '
          imagePullPolicy: IfNotPresent
          name: ${APPLICATION_NAME}
          ports:
          - containerPort: ${LISTEN_PORT}
            protocol: TCP
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 20
            successThreshold: 1
            tcpSocket:
              port: ${LISTEN_PORT}
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 20
            successThreshold: 1
            tcpSocket:
              port: ${LISTEN_PORT}
            timeoutSeconds: 5
          resources:
            requests:
              cpu: 200m
              memory: 100Mi
            limits:
              cpu: 1
              memory: 200Mi
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        serviceAccount: ${APPLICATION_NAME}-sa
        serviceAccountName: ${APPLICATION_NAME}-sa
        securityContext: {}
        terminationGracePeriodSeconds: 30
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${APPLICATION_NAME}
        from:
          kind: ImageStreamTag
          name: ${APPLICATION_NAME}:latest
      type: ImageChange


- kind: ServiceAccount
  apiVersion: v1
  metadata:
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}-sa

- apiVersion: v1
  kind: Service
  metadata:
    annotations:
    name: ${APPLICATION_NAME}
    labels:
      app: ${APPLICATION_NAME}
  spec:
    ports:
    - name: ${APPLICATION_NAME}
      port: ${LISTEN_PORT}
      protocol: TCP
      targetPort: ${LISTEN_PORT}
    selector:
      app: ${APPLICATION_NAME}
      deploymentconfig: ${APPLICATION_NAME}
    sessionAffinity: None
    type: ClusterIP

- apiVersion: v1
  kind: Route
  metadata:
    annotations:
      description: Route for Keycloak Gatekeeper's http service.
    name: ${APPLICATION_NAME}
    labels:
      app: ${APPLICATION_NAME}
  spec:
    tls:
      termination: edge
    to:
      kind: Service
      name: ${APPLICATION_NAME}
      
parameters:
- description: The name for the application.
  name: APPLICATION_NAME
  required: true
  value: grafeas
- description: The listen port of the App.
  name: LISTEN_PORT
  required: true
  value: "3000"