---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: inventory
  name: inventory-v1
spec:
  replicas: 1
  revisionHistoryLimit: 10
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: inventory
        version: v1
        region: central
    spec:
      containers:
      - name: inventory
        image: docker-registry.default.svc:5000/amazin-dev/inventory:0.0.1-SNAPSHOT
        imagePullPolicy: Always
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: v1
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
          - mountPath: /etc/inventory
            name: inventory-config-vol
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - configMap:
            defaultMode: 420
            name: inventory-v1-config
          name: inventory-config-vol
  test: false
  triggers:
    - type: ConfigChange
---
kind: Service
apiVersion: v1
metadata:
  name: inventory
  labels:
    app: inventory
spec:
  ports:
  - name: http
    protocol: TCP
    port: 8080
  selector:
    app: inventory
  type: ClusterIP
  sessionAffinity: None
