apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: web-prod-dc
objects:

- apiVersion: v1
  kind: Pod
  metadata:
    annotations:
      sidecar.istio.io/inject: 'false'
      openshift.io/scc: anyuid
    labels:
      app: web
      version: v1
    name: web
  spec:
    containers:
    - image: docker-registry.default.svc:5000/amazin-prod/web:0.0.1
      imagePullPolicy: Always
      livenessProbe:
        exec:
          command:
          - curl
          - -f
          - http://localhost:8080/
        failureThreshold: 3
        initialDelaySeconds: 10
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
      name: web
      ports:
      - containerPort: 8080
        protocol: TCP
      readinessProbe:
        exec:
          command:
          - curl
          - -f
          - http://localhost:8080/
        failureThreshold: 3
        initialDelaySeconds: 10
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File

- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: web
    name: web
  spec:
    ports:
    - port: 8080
      name: http
      protocol: TCP
      targetPort: 8080
    selector:
      app: web
    sessionAffinity: None
    type: ClusterIP
