apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRole
metadata:
  name: basket-prd-all-role
spec:
  rules:
  - services: ["basket-prd.amazin-prod.svc.cluster.local"]
    methods: ["GET", "POST", "PUT", "DELETE"]
---
apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRoleBinding
metadata:
  name: bind-basket-prd-all-role
spec:
  subjects:
  - user: "*"
  roleRef:
    kind: ServiceRole
    name: "basket-prd-all-role"