apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRoleBinding
metadata:
  name: bind-api-gateway-prd-all-role
spec:
  subjects:
  - user: "*"
  roleRef:
    kind: ServiceRole
    name: "api-gateway-prd-all-role"
---
apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRoleBinding
metadata:
  name: bind-user-prd-all-role
spec:
  subjects:
  - user: "*"
  roleRef:
    kind: ServiceRole
    name: "user-prd-all-role"

