---
apiVersion: v1
items:
- apiVersion: v1
  kind: Pod
  metadata:
    labels:
      app: amazin-dev1
      service: inventory
    name: inventory
  spec:
    containers:
    - name: inventory
      image: registry.access.redhat.com/codeready-workspaces/stacks-java
      imagePullPolicy: Always
      ports:
      - containerPort: 8080
      restartPolicy: Always
      env:
      - name: SPRING_PROFILES_ACTIVE
        value: dev
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: amazin-dev1
    name: inventory
  spec:
    ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      service: inventory
    sessionAffinity: None
    type: ClusterIP

- apiVersion: v1
  kind: Pod
  metadata:
    labels:
      app: amazin-dev1
      service: basket
    name: basket
  spec:
    containers:
    - name: basket
      image: registry.access.redhat.com/codeready-workspaces/stacks-java
      imagePullPolicy: Always
      restartPolicy: Always
      ports:
      - containerPort: 8080
      env:
      - name: SPRING_PROFILES_ACTIVE
        value: dev
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: amazin-dev1
    name: basket
  spec:
    ports:
      - port: 8080
        protocol: TCP
        targetPort: 8080
    selector:
      service: basket
    sessionAffinity: None
    type: ClusterIP

- apiVersion: v1
  kind: Pod
  metadata:
    labels:
      app: amazin-dev1
      service: user
    name: user
  spec:
    containers:
    - name: user
      image: registry.access.redhat.com/codeready-workspaces/stacks-java
      imagePullPolicy: Always
      restartPolicy: Always
      ports:
      - containerPort: 8080
      env:
      - name: SPRING_PROFILES_ACTIVE
        value: dev
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: amazin-dev1
    name: user
  spec:
    ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      service: user
    sessionAffinity: None
    type: ClusterIP

- apiVersion: v1
  kind: Pod
  metadata:
    labels:
      app: amazin-dev1
      service: api-gateway
    name: api-gateway
  spec:
    containers:
    - name: api-gateway
      image: registry.access.redhat.com/codeready-workspaces/stacks-java
      imagePullPolicy: Always
      restartPolicy: Always
      ports:
      - containerPort: 8080
      env:
      - name: SPRING_PROFILES_ACTIVE
        value: dev
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: amazin-dev1
    name: api-gateway
  spec:
    ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      service: api-gateway
    sessionAffinity: None
    type: ClusterIP

kind: List
