server:
  port: 8080

basket:
  host: istio-ingress.istio-system.svc

inventory:
  host: istio-ingress.istio-system.svc

user:
  host: istio-ingress.istio-system.svc

opentracing:
  jaeger:
    http-sender:
      url: = http://jaeger-collector.istio-system:14268