apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJuZXh1cy1kb2NrZXItY2ljZC5hcHBzLWNyYy50ZXN0aW5nIjp7InVzZXJuYW1lIjoiYWRtaW4iLCJwYXNzd29yZCI6Im1vbmtleTEyMyIsImVtYWlsIjoiZG9ja2VyQGVtYWlsLmNvbSIsImF1dGgiOiJZV1J0YVc0NmJXOXVhMlY1TVRJeiJ9fX0=
kind: Secret
metadata:
  creationTimestamp: null
  name: crc-nexus-dockercfg
type: kubernetes.io/dockerconfigjson