apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
#- datr-eu-certs.yaml
#- resource-quota.yaml
#- limit-range.yaml
- crc-nexus-dockercfg-secret.yaml
- rhpds-nexus-dockercfg-secret.yaml
- datreu-nexus-dockercfg-secret.yaml
- serviceaccounts.yaml
- jenkins-edit-rb.yaml
patchesStrategicMerge:
- dockercfg-default-patch.yaml
- dockercfg-builder-patch.yaml
- dockercfg-deployer-patch.yaml
commonAnnotations:
  author: Justin Davis