kind: Deployment
apiVersion: apps/v1
metadata:
  name: deployment
spec:
  template:
    spec:
      serviceAccountName: user-sa
      containers:
        - name: container 
          image: nexus3-docker-cicd.apps.ocp4.datr.eu/repository/docker/amazin-dev/user:cbc06c6
          env:
          - name: SPRING_PROFILES_ACTIVE
            value: dev
          volumeMounts:
            - mountPath: /config
              name: user-config-vol      
      volumes:
      - configMap:
          defaultMode: 420
          name: user-config
        name: user-config-vol                                     