apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: inventory-lb
spec:
  destination:
    name: inventory
  precedence: 1
  route:
  - labels:
      version: v1
    weight: 0
  - labels:
      version: v2
    weight: 0
  - labels:
      version: v3
    weight: 100
---
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: basket-lb
spec:
  destination:
    name: basket
  precedence: 1
  route:
  - labels:
      version: v1
    weight: 100
---
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: user-lb
spec:
  destination:
    name: user
  precedence: 1
  route:
  - labels:
      version: v1
    weight: 100
---
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: gateway-lb
spec:
  destination:
    name: api-gateway
  precedence: 1
  route:
  - labels:
      version: v1
    weight: 100