---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: inventory
spec:
  hosts:
  - "*"
  gateways:
  - amazin-gateway-prod
  http:
  - match:
    - uri:
        prefix: /products
    route:
    - destination:
        host: inventory
        subset: v1
      weight: 100
    - destination:
        host: inventory
        subset: v2
      weight: 0
    - destination:
        host: inventory
        subset: v3
      weight: 0