---
apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: git-checkout
spec:
  serviceAccount: default
  inputs:
    resources:
      - name: gitssh
        resourceSpec:
          type: git
          params:
            - name: revision
              value: master
            - name: url
              value: https://github.com/justindav1s/data-model.git
  taskSpec:
    inputs:
      resources:
        - name: gitssh
          type: git
    steps:
      - name: echo-readme
        image: docker-registry.default.svc:5000/tekton-test2/java-builder
        command: ["/bin/bash"]
        args: ["-c", "mkdir -p /workspace/gitssh/target/classes; mvn -f /workspace/gitssh/pom.xml -U -s /workspace/gitssh/settings.xml -Dmaven.wagon.http.ssl.insecure=true -Dmaven.wagon.http.ssl.allowall=true package -Dspring.profiles.active=dev -DskipTests"]
#        args: ["-c", "cat /workspace/gitssh/README.md"]
#      - name: mavn-build
#        image: registry.access.redhat.com/openshift3/jenkins-agent-maven-35-rhel7
#        command: ["/bin/bash"]
#        args: ["-c", "mvn -f /workspace/gitssh -U -B -q -s settings.xml -Dmaven.wagon.http.ssl.insecure=true -Dmaven.wagon.http.ssl.allowall=true clean package -Dspring.profiles.active=dev -DskipTests"]
#        volumeMounts:
#          - name: workspace
#            mountPath: "/workspace"
#    volumes:
#      - name: workspace
#        emptyDir: {}